### ISSUE TITLE
Ciertas carpetas ocurrió error en descarga

### ISSUE THREAD

**Issue by glbello** [open-source-uc/webcursinc#15]
Al pasar por el curso de inglés RII6001, 

```bash
ERROR Parsing folder url
Couldn't parse a folder url
javascript:document.getElementById('sakai_action').value='doNavigate';document.getElementById('collectionId').value='/group/rii6001-6-22-2017/Protocols _ Attendance Policy/';document.getElementById('navRoot').value='';document.getElementById('showForm').submit();

ERROR Parsing folder url
Couldn't parse a folder url
javascript:document.getElementById('sakai_action').value='doNavigate';document.getElementById('collectionId').value='/group/rii6001-6-22-2017/Protocols _ Attendance Policy/';document.getElementById('navRoot').value='';document.getElementById('showForm').submit();
```

Adjunto las carpetas que no se parsearon:

![01](https://user-images.githubusercontent.com/13740193/29006869-0e18c1d4-7ac6-11e7-8c6d-e04274fd4a25.jpg)
![02](https://user-images.githubusercontent.com/13740193/29006867-0e0effc8-7ac6-11e7-9493-6cb6cf39a527.jpg)
![03](https://user-images.githubusercontent.com/13740193/29006868-0e139984-7ac6-11e7-9da9-451f6fff3230.jpg)

**Comment by negebauer** [comment]
Prueba con `v1.0.8`

**Comment by glbello** [comment]
Funcionó a la perfección clonando el repo, mil gracias por esta app que es tan útil :'D
